/*
 * HelloApiSchema
 *
 * Practice api schema
 *
 * API version: 1.0.0
 * Contact: doriven@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateUserInput struct {

	EmailAddress string `json:"email_address"`

	LastName string `json:"last_name"`

	FirstName string `json:"first_name"`

	Birthday string `json:"birthday"`

	Address string `json:"address"`
}

// AssertCreateUserInputRequired checks if the required fields are not zero-ed
func AssertCreateUserInputRequired(obj CreateUserInput) error {
	elements := map[string]interface{}{
		"email_address": obj.EmailAddress,
		"last_name": obj.LastName,
		"first_name": obj.FirstName,
		"birthday": obj.Birthday,
		"address": obj.Address,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCreateUserInputRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateUserInput (e.g. [][]CreateUserInput), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateUserInputRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateUserInput, ok := obj.(CreateUserInput)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateUserInputRequired(aCreateUserInput)
	})
}
